version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    container_name: nginx_shortner
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    container_name: app_shortner
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgres
    environment:
      POSTGRES_DB: db_links_shortner
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "8101:5432"
    container_name: db_links

